name: Validate

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  validate:
    name: HACS and Hassfest
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
